version: '2'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/home/node/app
